name: 'nyc_taxi_trip_duration'
version: '1.0.0'
config-version: 2

profile: 'nyc_taxi_trip_duration'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: [ "models" ]
analysis-paths: [ "analyses" ]
test-paths: [ "tests" ]
seed-paths: [ "seeds" ]
macro-paths: [ "macros" ]
snapshot-paths: [ "snapshots" ]

target-path: "target"  # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

seeds:
  training_trips:
    +enabled: true
    +schema: nyc_taxi_trip_duration

#seeds:
#  - name: training_trips
#    description: Seed data for training trips
#    seed_enabled: true
#    quoting: double
#    delimiter: ','
#    quotechar: '"'
#    path: seeds/nyc-taxi-trip-duration/train.csv  # Relative path to the seed file
#    schema: nyc_taxi_trip_duration  # The target schema where the seed table will be created
#    database: dogwood-cinema-393905  # Replace with your BigQuery profile name
#    table: training_trips  # The target table name
#    meta:
#      type: seed
#    tests:
#      - unique_id # Configuring models

vars:
  "dbt_ml:audit_schema": "audit"
  "dbt_ml:audit_table": "ml_models"
on-run-start:
  - '{% do adapter.create_schema(api.Relation.create(target.project, "audit")) %}'
  - "{{ dbt_ml.create_model_audit_table() }}"

# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  +persist_docs:
    relation: true
    columns: true
  +labels:
    owner: "ingaleniranjan365"
    env: "{{ target.name }}"
    status: experimental
    interval: daily
  dbt_ml:
    ml:
      enabled: true
      schema: ml
      materialized: model
      post-hook: "{{ dbt_ml.model_audit() }}"
#  kaggle:
#    nyc_taxi_trip_duration:
#      +tags:
#        - "nyc-trip-duration-prediction"
#      presentation:
#        +schema: nyc_taxi_trip_duration
#        +materialized: table
#        +tags:
#          - "presentation"
#      staging:
#        # add a schema so that the datasets have a staging suffix
#        +schema: nyc_taxi_trip_duration_staging
#        +materialized: view
#        +tags:
#          - "staging"
#      raw:
#        +schema: nyc_taxi_trip_duration_raw
#        +materialized: view
#        +tags:
#          - "raw"
